### ISSUE TITLE
Replace init with initMod

### ISSUE THREAD

**Issue by JoJota** [boroda74/Vivaldi-Mods#1]
Hi,

thank you for the work with the mods. I just tried to run them, but there was a reference error with that line:

https://github.com/boroda74/Vivaldi-Mods/blob/b36751728c48be2b0ce1b7ac8d789ccd2293fe5e/Mods/sessions-panel.js#L1573

After changing the reference to `initMod` instead of `init` the error disappeared and the mod loaded. This might also fix the problem [here](https://forum.vivaldi.net/post/516930).

**Comment by boroda74** [comment]
Done.
